version: '3.6'

services:
  sql:
    image: mysql:5.7
    container_name: sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - MYSQL_DATABASE=sql_recipes
    expose:
      - 3306
    networks:
      - db_network
      
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
      MONGO_INITDB_DATABASE: mongo_recipes
    expose:
      - 27017 
    command: --quiet
    networks:
      - db_network

  api:
    build: ./api
    container_name: api
    restart: always
    expose:
      - 8000
    depends_on:
      - sql
    networks:
      - db_network
      - ext_network
      
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    expose:
      - 8080
    networks:
      - ext_network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000" 
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - ext_network 

networks:
  db_network: {}
  ext_network: {}
